#ifndef XML_TAGS_H
#define XML_TAGS_H

#define TAG_LAYOUT					"layout"
#define TAG_CLASSIC					"classic"
#define TAG_ENGINE					"engine"
#define TAG_MODERN					"modern"
#define TAG_GAUGE						"gauge"
#define TAG_GENERIC					"generic"
#define TAG_ENGINE_MINI				"engine-mini"

#define TAG_POS						"pos"
#define TAG_TOP_LEFT					"top-left"
#define TAG_TOP_MIDDLE				"top-middle"
#define TAG_TOP_RIGHT				"top-right"
#define TAG_BOTTOM_LEFT				"bottom-left"
#define TAG_BOTTOM_MIDDLE			"bottom-middle"
#define TAG_BOTTOM_RIGHT			"bottom-right"

#define TAG_SCALE						"scale"
#define TAG_PARAMS					"parameters"
#define TAG_PARAM						"parameter"
#define TAG_COUNT						"count"
#define TAG_HIGH						"high"
#define TAG_LOW						"low"
#define TAG_ITEM						"item"
#define TAG_ARC_START				"arc-start"
#define TAG_ARC_LEN					"arc-length"
#define TAG_DECIMALS					"decimals"
#define TAG_RANGE						"range"
#define TAG_LIMITS					"limits"
#define TAG_GREEN						"green"
#define TAG_YELLOW					"yellow"
#define TAG_WHITE						"white"
#define TAG_HI_LIMIT					"high-limit"
#define TAG_LO_LIMIT					"low-limit"
#define TAG_YES						"yes"
#define TAG_NO							"no"
#define TAG_UNIT						"unit"
#define TAG_LABEL						"label"
#define TAG_SYSTEM_UNIT				"system-unit"
#define TAG_FRAME						"frame"
#define TAG_TYPE						"type"
#define TAG_MAJOR						"major"
#define TAG_MINOR						"minor"
#define TAG_MULT						"mult"
#define TAG_ARC						"arc"
#define TAG_DUMPING					"dumping"

#define TAG_VELOCITY					"velocity"
#define TAG_VY							"vy"
#define TAG_VREF						"vref"
#define TAG_VFE1						"vfe1"
#define TAG_VFE2						"vfe2"
#define TAG_VSW						"vsw"

#define TAG_ALARM						"alarm"
#define TAG_DELAY						"delay"
#define TAG_STATUS					"status"
#define TAG_ENABLED					"enabled"
#define TAG_DISABLED					"disabled"
#define TAG_USER						"user"

#define TAG_R							"r"
#define TAG_PHI						"phi"
#define TAG_TEXT						"text"
#define TAG_SIZE						"size"
#define TAG_BIG						"big"
#define TAG_WIDTH						"width"
#define TAG_HEIGHT					"height"
#define TAG_GAP						"gap"

#define TAG_HOT						"hot"
#define TAG_COLD						"cold"

#define TAG_AIRSPEED					"airspeed"
#define TAG_ALTITUDE					"altitude"
#define TAG_VARIO						"vario"
#define TAG_OIL_PRESS				"oil-pressure"
#define TAG_OIL_TEMP					"oil-temp"
#define TAG_VOLTAGE					"voltage"
#define TAG_CURRENT					"current"
#define TAG_WATER_TEMP				"water-temp"
#define TAG_CARBURETOR				"carburetor"
#define TAG_MANIFOLD					"manifold"
#define TAG_FUEL_PRESS				"fuel-pressure"
#define TAG_FUEL_LEVEL				"fuel-level"
#define TAG_FUEL_FLOW				"fuel-flow"
#define TAG_RPM						"rpm"
#define TAG_ENGINE_TIME				"engine-time"
#define TAG_EGT						"egt"
#define TAG_CHT						"cht"
#define TAG_TAS						"tas"
#define TAG_QNH						"qnh"
#define TAG_ENDURANCE				"endurance"
#define TAG_AVG_FUEL_FLOW			"avg-fuel-flow"
#define TAG_TURN_BANK				"turn-bank"

#define TAG_THIRD_NEEDLE			"third-needle"

#define TAG_BAR						"bar"
#define TAG_TOP_BOTTOM				"top-bottom"
#define TAG_BOTTOM_TOP				"bottom-top"
#define TAG_LEFT_RIGHT				"left-right"
#define TAG_RIGHT_LEFT				"right-left"


#endif
